version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/PDP/PlantGrowthModule"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/PDP/DataDownloadTool"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
